# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false

  config.vm.box = "generic/debian12"
  config.vm.box_version = "4.3.12"

  config.vm.define "triouS", primary: true do |s|
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provision :shell, path: "scripts/server.sh"
    s.vm.hostname = "triouS"
    s.vm.provider :virtualbox do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  config.vm.define "triouSW" do |sw|
    sw.vm.network "private_network", ip: "192.168.56.111"
    sw.vm.provision :shell, path: "scripts/worker.sh"
    sw.vm.hostname = "triouSW"
    sw.vm.provider :virtualbox do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

end
